name: subgraph-query
jobs:
  cases:
    steps:
    - uri: fs/build
      method: subgraphQuery
      input:
        subgraphAuthor: ensdomains
        subgraphName: ens
        query: "{\ndomains(first: 5) {\nid\nname\nlabelName\nlabelhash\n}\n}"
